#!/bin/sh
# Pushes all local changes up to each JSTransformer.
# Copyright © 2018 RobLoach
# MIT-licensed

[ -f config.ini ] && \
root=$(awk -F '=' '{if (! ($0 ~ /^;/) && $0 ~ /root/) print $2}' config.ini)

cwd="`pwd`"

for d in `echo ${root}jstransformer*/`; do
  repo="`basename $d`"
  echo "Processing $repo"
  cd "$d"
  git add -A
  git commit -m "Update Boilerplate"
  git push origin master

  cd "$cwd"
done
